package InterfazGrafica;

import ageofthreads.Almacen;
import ageofthreads.Guerrero;
import ageofthreads.Simulador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author a
 */
public class GUI extends javax.swing.JFrame {
    private Simulador simulador;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        simulador =new Simulador();
        
        
        int capacidadComida =simulador.getCentroUrbano().getAlmacenes().get(0).getCapacidadMax();
        capacidadComidaTexto.setText("/ " +String.valueOf(capacidadComida));
        int capacidadOro =simulador.getCentroUrbano().getAlmacenes().get(2).getCapacidadMax();
        CapacidadOroTexto3.setText("/ " +String.valueOf(capacidadOro));
        int capacidadMadera =simulador.getCentroUrbano().getAlmacenes().get(1).getCapacidadMax();
        capacidadMaderaTexto.setText("/ " + String.valueOf(capacidadMadera));
        
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
            actualizarCantidadRecursos();
            actualizarListas();
        
            }
        });
        timer.start();
    }
    private void actualizarListas(){
        
        DefaultListModel<String> tesoreria = simulador.getCentroUrbano().getAlmacenes().get(2).combinarListasOcupacionAlmacen();
        jListTesoreria.setModel(tesoreria);
        DefaultListModel<String> aserradero = simulador.getCentroUrbano().getAlmacenes().get(1).combinarListasOcupacionAlmacen();
        jListAserradero.setModel(aserradero);
        DefaultListModel<String> granero = simulador.getCentroUrbano().getAlmacenes().get(0).combinarListasOcupacionAlmacen();
        jListGranero.setModel(granero);
        
        DefaultListModel<String> mina = simulador.getCentroUrbano().getAreasRecursos().get(2).combinarListasOcupacionArea();
        jListMina.setModel(mina);
        DefaultListModel<String> granja = simulador.getCentroUrbano().getAreasRecursos().get(0).combinarListasOcupacionArea();
        jListGranja.setModel(granja);
        DefaultListModel<String> bosque = simulador.getCentroUrbano().getAreasRecursos().get(1).combinarListasOcupacionArea();
        jListBosque.setModel(bosque);
        
        
        DefaultListModel<String> cuartel = simulador.getCentroUrbano().listaCuartel();
        jListCuartel.setModel(cuartel);
        DefaultListModel<String> casa = simulador.getCentroUrbano().mostrarListaCasa();
        jListCasaPrincipal.setModel(casa);
        DefaultListModel<String> plazaCentral = simulador.getCentroUrbano().mostrarPlazaCentral();
        jListPlazaCentral.setModel(plazaCentral);
        DefaultListModel<String> areaRecuperacion = simulador.getCentroUrbano().combinarListasAreaRecuperacion();
        jListAreaRecuperacion.setModel(areaRecuperacion);
        
        DefaultListModel<String> zonaPreparacion = simulador.getCampamento().listaZonaPreparacion();
        jListZonaPreparacion.setModel(zonaPreparacion);
        
        DefaultListModel<String> campamento = simulador.getCampamento().listaCampamento();
        jListCampamentoBarbaro.setModel(campamento);
       
        
    }
   
    private void actualizarCantidadRecursos() {
        Almacen comida = simulador.getCentroUrbano().getAlmacenes().get(0); // comida
        Almacen madera = simulador.getCentroUrbano().getAlmacenes().get(1); // madera
        Almacen oro = simulador.getCentroUrbano().getAlmacenes().get(2);    // oro

        comidaTexto.setText("Comida: " + comida.getCantidad());
        maderaTexto.setText("Madera: " + madera.getCantidad());
        oroTexto.setText("Oro: " + oro.getCantidad());
    }
    
    
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecursosYBotonesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        oroTexto = new javax.swing.JLabel();
        maderaTexto = new javax.swing.JLabel();
        comidaTexto = new javax.swing.JLabel();
        jToggleButtonAlarma = new javax.swing.JToggleButton();
        jToggleButtonPausa = new javax.swing.JToggleButton();
        capacidadMaderaTexto = new javax.swing.JLabel();
        capacidadComidaTexto = new javax.swing.JLabel();
        CapacidadOroTexto3 = new javax.swing.JLabel();
        AlmacenesPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTesoreria = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListGranero = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAserradero = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CentroUrbanoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCuartel = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListAreaRecuperacion = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListPlazaCentral = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListCasaPrincipal = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AreasPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListBosque = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jListGranja = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jListMina = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Barbaros = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jListZonaPreparacion = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        jListCampamentoBarbaro = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TiendaPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButtonGuerrero = new javax.swing.JButton();
        jButtonAldeano = new javax.swing.JButton();
        jButtonMejoraAlmacenes = new javax.swing.JButton();
        jButtonMejoraArmas = new javax.swing.JButton();
        jButtonMejoraHerramientas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RecursosYBotonesPanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Recursos");

        jToggleButtonAlarma.setText("Activar alarma");
        jToggleButtonAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAlarmaActionPerformed(evt);
            }
        });

        jToggleButtonPausa.setText("Pausar");
        jToggleButtonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPausaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RecursosYBotonesPanelLayout = new javax.swing.GroupLayout(RecursosYBotonesPanel);
        RecursosYBotonesPanel.setLayout(RecursosYBotonesPanelLayout);
        RecursosYBotonesPanelLayout.setHorizontalGroup(
            RecursosYBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecursosYBotonesPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(oroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CapacidadOroTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maderaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capacidadMaderaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(comidaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capacidadComidaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonAlarma)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonPausa)
                .addContainerGap())
        );
        RecursosYBotonesPanelLayout.setVerticalGroup(
            RecursosYBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecursosYBotonesPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(RecursosYBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecursosYBotonesPanelLayout.createSequentialGroup()
                        .addGroup(RecursosYBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comidaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oroTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maderaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(capacidadMaderaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidadComidaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CapacidadOroTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecursosYBotonesPanelLayout.createSequentialGroup()
                        .addGroup(RecursosYBotonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonAlarma)
                            .addComponent(jToggleButtonPausa))
                        .addGap(26, 26, 26))))
        );

        AlmacenesPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setText("Almacenes");

        jScrollPane1.setViewportView(jListTesoreria);

        jScrollPane2.setViewportView(jListGranero);

        jScrollPane4.setViewportView(jListAserradero);

        jLabel2.setText("Aserradero");

        jLabel5.setText("Tesoreria");

        jLabel10.setText("Granero");

        javax.swing.GroupLayout AlmacenesPanelLayout = new javax.swing.GroupLayout(AlmacenesPanel);
        AlmacenesPanel.setLayout(AlmacenesPanelLayout);
        AlmacenesPanelLayout.setHorizontalGroup(
            AlmacenesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlmacenesPanelLayout.createSequentialGroup()
                .addGroup(AlmacenesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlmacenesPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(AlmacenesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AlmacenesPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel5))
                    .addGroup(AlmacenesPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel10))
                    .addGroup(AlmacenesPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(AlmacenesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AlmacenesPanelLayout.setVerticalGroup(
            AlmacenesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlmacenesPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        CentroUrbanoPanel.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setText("Centro urbano");

        jScrollPane3.setViewportView(jListCuartel);

        jScrollPane5.setViewportView(jListAreaRecuperacion);

        jScrollPane6.setViewportView(jListPlazaCentral);

        jScrollPane8.setViewportView(jListCasaPrincipal);

        jLabel6.setText("Cuartel");

        jLabel11.setText("Plaza Central");

        jLabel12.setText("Área de Recuperación");

        jLabel13.setText("Casa Principal");

        javax.swing.GroupLayout CentroUrbanoPanelLayout = new javax.swing.GroupLayout(CentroUrbanoPanel);
        CentroUrbanoPanel.setLayout(CentroUrbanoPanelLayout);
        CentroUrbanoPanelLayout.setHorizontalGroup(
            CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentroUrbanoPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(102, 102, 102))
            .addGroup(CentroUrbanoPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CentroUrbanoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(203, 203, 203))
            .addGroup(CentroUrbanoPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(90, 90, 90))
        );
        CentroUrbanoPanelLayout.setVerticalGroup(
            CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentroUrbanoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addGroup(CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(CentroUrbanoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addGap(34, 34, 34))
        );

        AreasPanel.setBackground(new java.awt.Color(0, 204, 153));

        jLabel7.setText("Áreas de recursos");

        jScrollPane7.setViewportView(jListBosque);

        jScrollPane9.setViewportView(jListGranja);

        jScrollPane11.setViewportView(jListMina);

        jLabel14.setText("Mina");

        jLabel15.setText("Bosque");

        jLabel17.setText("Granja");

        javax.swing.GroupLayout AreasPanelLayout = new javax.swing.GroupLayout(AreasPanel);
        AreasPanel.setLayout(AreasPanelLayout);
        AreasPanelLayout.setHorizontalGroup(
            AreasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreasPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AreasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreasPanelLayout.createSequentialGroup()
                        .addGroup(AreasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(116, 116, 116))))
        );
        AreasPanelLayout.setVerticalGroup(
            AreasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Barbaros.setBackground(new java.awt.Color(255, 102, 102));

        jLabel9.setText("Bárbaros");

        jScrollPane10.setViewportView(jListZonaPreparacion);

        jScrollPane12.setViewportView(jListCampamentoBarbaro);

        jLabel16.setText("Zona de Preparación");

        jLabel18.setText("Campamento Bárbaro");

        javax.swing.GroupLayout BarbarosLayout = new javax.swing.GroupLayout(Barbaros);
        Barbaros.setLayout(BarbarosLayout);
        BarbarosLayout.setHorizontalGroup(
            BarbarosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarbarosLayout.createSequentialGroup()
                .addGroup(BarbarosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BarbarosLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(BarbarosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BarbarosLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel9))
                    .addGroup(BarbarosLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel16))
                    .addGroup(BarbarosLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BarbarosLayout.setVerticalGroup(
            BarbarosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarbarosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TiendaPanel.setBackground(new java.awt.Color(255, 204, 51));

        jLabel8.setText("Tienda");

        jButtonGuerrero.setText("Guerrero  50 Comida  80 oro 50 madera");
        jButtonGuerrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuerreroActionPerformed(evt);
            }
        });

        jButtonAldeano.setText("Aldeano      50 comida");
        jButtonAldeano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAldeanoActionPerformed(evt);
            }
        });

        jButtonMejoraAlmacenes.setText("Mejora Almacenes       150 madera      50 oro");
        jButtonMejoraAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMejoraAlmacenesActionPerformed(evt);
            }
        });

        jButtonMejoraArmas.setText("Mejora Armas      150 comida      100 oro");
        jButtonMejoraArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMejoraArmasActionPerformed(evt);
            }
        });

        jButtonMejoraHerramientas.setText("Mejora Heramientas      120 madera      80 oro");
        jButtonMejoraHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMejoraHerramientasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TiendaPanelLayout = new javax.swing.GroupLayout(TiendaPanel);
        TiendaPanel.setLayout(TiendaPanelLayout);
        TiendaPanelLayout.setHorizontalGroup(
            TiendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TiendaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(145, 145, 145))
            .addGroup(TiendaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TiendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGuerrero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAldeano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMejoraHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMejoraArmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMejoraAlmacenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TiendaPanelLayout.setVerticalGroup(
            TiendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TiendaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jButtonAldeano)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuerrero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMejoraHerramientas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMejoraArmas)
                .addGap(18, 18, 18)
                .addComponent(jButtonMejoraAlmacenes)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AlmacenesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CentroUrbanoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RecursosYBotonesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TiendaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Barbaros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RecursosYBotonesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CentroUrbanoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AlmacenesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AreasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TiendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Barbaros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAlarmaActionPerformed
        // TODO add your handling code here:
                                                           
    if (jToggleButtonAlarma.isSelected()) {
        simulador.getCentroUrbano().activarEmergencia();
        jToggleButtonAlarma.setText("Desactivar alarma");
    } else {
        simulador.getCentroUrbano().desactivarEmergencia();
        jToggleButtonAlarma.setText("Activar alarma");
    }


    }//GEN-LAST:event_jToggleButtonAlarmaActionPerformed

    private void jButtonMejoraAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMejoraAlmacenesActionPerformed
        // TODO add your handling code here:
        simulador.mejorarAlmacenes();
        jButtonMejoraAlmacenes.setText("Mejora Almacenes ("+simulador.getCentroUrbano().getNivelMejoraAlmacenes() +")     150 madera      50 oro");
        int capacidadComida =simulador.getCentroUrbano().getAlmacenes().get(0).getCapacidadMax();
        capacidadComidaTexto.setText(String.valueOf(capacidadComida));
        int capacidadOro =simulador.getCentroUrbano().getAlmacenes().get(2).getCapacidadMax();
        CapacidadOroTexto3.setText(String.valueOf(capacidadOro));
        int capacidadMadera =simulador.getCentroUrbano().getAlmacenes().get(1).getCapacidadMax();
        capacidadMaderaTexto.setText(String.valueOf(capacidadMadera));
    }//GEN-LAST:event_jButtonMejoraAlmacenesActionPerformed

    private void jButtonGuerreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuerreroActionPerformed
        // TODO add your handling code here:
            simulador.comprarGuerrero();
                   
    }//GEN-LAST:event_jButtonGuerreroActionPerformed

    private void jButtonAldeanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAldeanoActionPerformed
        // TODO add your handling code here:
        simulador.comprarAldeano();
    }//GEN-LAST:event_jButtonAldeanoActionPerformed

    private void jButtonMejoraHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMejoraHerramientasActionPerformed
        // TODO add your handling code here:
        simulador.mejorarHerramientas();
        
        jButtonMejoraHerramientas.setText("Mejora Heramientas ("+simulador.getCentroUrbano().getNivelMejoraHerramientas() +")    120 madera      80 oro");                                                                             
        
    }//GEN-LAST:event_jButtonMejoraHerramientasActionPerformed

    private void jButtonMejoraArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMejoraArmasActionPerformed
        // TODO add your handling code here:
        simulador.mejorarArmas();
        jButtonMejoraArmas.setText("Mejora Armas ("+simulador.getCentroUrbano().getNivelMejoraArmas()+")     150 comida      100 oro");
    }//GEN-LAST:event_jButtonMejoraArmasActionPerformed

    private void jToggleButtonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPausaActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonPausa.isSelected()) {
            // El botón está en modo "pausado"
            simulador.getControlEjecucion().pausar();
            jToggleButtonPausa.setText(" Reanudar");
        } else {
            // El botón está en modo "activo"
            simulador.getControlEjecucion().reanudar();
            jToggleButtonPausa.setText(" Pausar");
        }
    }//GEN-LAST:event_jToggleButtonPausaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlmacenesPanel;
    private javax.swing.JPanel AreasPanel;
    private javax.swing.JPanel Barbaros;
    private javax.swing.JLabel CapacidadOroTexto3;
    private javax.swing.JPanel CentroUrbanoPanel;
    private javax.swing.JPanel RecursosYBotonesPanel;
    private javax.swing.JPanel TiendaPanel;
    private javax.swing.JLabel capacidadComidaTexto;
    private javax.swing.JLabel capacidadMaderaTexto;
    private javax.swing.JLabel comidaTexto;
    private javax.swing.JButton jButtonAldeano;
    private javax.swing.JButton jButtonGuerrero;
    private javax.swing.JButton jButtonMejoraAlmacenes;
    private javax.swing.JButton jButtonMejoraArmas;
    private javax.swing.JButton jButtonMejoraHerramientas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListAreaRecuperacion;
    private javax.swing.JList<String> jListAserradero;
    private javax.swing.JList<String> jListBosque;
    private javax.swing.JList<String> jListCampamentoBarbaro;
    private javax.swing.JList<String> jListCasaPrincipal;
    private javax.swing.JList<String> jListCuartel;
    private javax.swing.JList<String> jListGranero;
    private javax.swing.JList<String> jListGranja;
    private javax.swing.JList<String> jListMina;
    private javax.swing.JList<String> jListPlazaCentral;
    private javax.swing.JList<String> jListTesoreria;
    private javax.swing.JList<String> jListZonaPreparacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToggleButton jToggleButtonAlarma;
    private javax.swing.JToggleButton jToggleButtonPausa;
    private javax.swing.JLabel maderaTexto;
    private javax.swing.JLabel oroTexto;
    // End of variables declaration//GEN-END:variables
}
